Task 2::Components
i-obraztsov/junior-course-boilerplate pull request #2
Opened 2021-01-15 21:36 UTC by i-obraztsov

2021-01-16 07:41 UTC, vislogurov requested changes

2021-01-16 07:41 UTC, vislogurov commented on src/styles.js
> +export const AppContent = styled.main`
Почему бы не хранить каждый стиль непосредственно рядом с компонентом? Если нужно будет добавить стилевые правила, то придётся всю простыню в этом файле перебирать.

2021-01-16 07:41 UTC, vislogurov commented on src/components/App/index.js
> +          {products.map(({id, name, in_stock, price, sub_price, rating}) => (
Нужно предусмотреть какой-то UI на случай, если массив produсts пустой или вовсе не пришел. Например "Список товаров пуст"

2021-01-16 20:22 UTC, i-obraztsov commented on src/styles.js
> +export const AppContent = styled.main`
Исправил

2021-01-16 20:22 UTC, i-obraztsov commented on src/components/App/index.js
> +          {products.map(({id, name, in_stock, price, sub_price, rating}) => (
Добавил компонент заглушку

2021-01-18 06:45 UTC, vislogurov approved these changes

2021-01-18 07:38 UTC, merged