Task 5 :: Context
i-obraztsov/junior-course-boilerplate pull request #5
Opened 2021-02-02 09:35 UTC by i-obraztsov

2021-02-03 16:27 UTC, vislogurov requested changes

2021-02-03 16:27 UTC, vislogurov commented on src/components/App/index.js
> +    if (event.target.type === 'checkbox') {
Кажется излишним проверять на то, чекбокс это или нет, а потом ещё раз проверять чекнут он или нет.
Это же решается через `onChange={handleChange}` на уровне самого компонента чекбокса — это уже чекбокс и он уже чекнут.

Плюс ты дублируешь эту же проверку в withContext.js. Зачем?

2021-02-04 20:42 UTC, i-obraztsov commented on src/components/App/index.js
> +    if (event.target.type === 'checkbox') {
Да, немного странно получилось

2021-02-05 15:23 UTC, vislogurov approved these changes

2021-02-06 13:47 UTC, merged