Task 6 :: Redux
i-obraztsov/junior-course-boilerplate pull request #6
Opened 2021-02-07 19:37 UTC by i-obraztsov

2021-02-09 07:57 UTC, vislogurov requested changes

2021-02-09 07:57 UTC, vislogurov commented on src/components/Products/index.js
> +    const filtered = filterGoods(products, {
В таком случае товары будут "вычисляться" каждый рендер, даже если товары не изменились. Выглядит как место для применения мемоизации.

2021-02-09 12:01 UTC, i-obraztsov commented on src/components/Products/index.js
> +    const filtered = filterGoods(products, {
Добавил мемоизацию

2021-02-09 12:53 UTC, vislogurov requested changes

2021-02-09 12:53 UTC, vislogurov commented on src/components/Products/index.js
> +    const filtered = memoizeFilter(products, {
Я не сразу увидел, что внутри рендера это делаешь( render должен быть максимально  "чистым" и отвечать только за рендер отображения (КО). Сейчас же он у тебя ещё и фильтрацией занимается. Получается компонет уже слишком много о структуре стора знает. Почему бы тогда фильтрацию не сделать в контейнере, который со стором и общается напрямую? А в Products уже передавать только список для отрисовки

2021-02-09 16:55 UTC, i-obraztsov commented on src/components/Products/index.js
> +    const filtered = memoizeFilter(products, {
Да, так будет лучше)
А что значит КО?

2021-02-10 12:58 UTC, vislogurov commented on src/components/Products/index.js
> +    const filtered = memoizeFilter(products, {
КО — Капитан Очевидность)

2021-02-10 12:59 UTC, vislogurov approved these changes

2021-02-10 18:19 UTC, merged