Task 7 :: Redux Modularization
i-obraztsov/junior-course-boilerplate pull request #7
Opened 2021-02-14 19:27 UTC by i-obraztsov

2021-02-16 13:44 UTC, vislogurov requested changes

2021-02-16 13:44 UTC, vislogurov commented on src/components/Pagination/style.js
> +          'box-shadow': 'none',
`poiner-events: none`, чтобы гарантированно не вызвать событие

2021-02-16 13:44 UTC, vislogurov commented on src/components/Pagination/index.js
> +      currentPage === pageNumber ||
почему условия тут отличаются от условий `isDisable` в Button? У тебя клик по кнопке должен либо обновлять/сбрасывать состояние пагинации. Либо вызываться вообще. Вот как раз второй случай закроется в случае `isDisabled = true` (тогда событие не выстрелит вообще)

2021-02-16 18:47 UTC, i-obraztsov commented on src/components/Pagination/style.js
> +          'box-shadow': 'none',
Добавил

2021-02-16 18:47 UTC, i-obraztsov commented on src/components/Pagination/index.js
> +      currentPage === pageNumber ||
Исправил

2021-02-17 09:49 UTC, vislogurov approved these changes

2021-02-17 10:00 UTC, merged