Task 8 :: Роутинг
i-obraztsov/junior-course-boilerplate pull request #8
Opened 2021-02-20 01:09 UTC by i-obraztsov

2021-02-24 16:28 UTC, vislogurov requested changes

2021-02-24 16:28 UTC, vislogurov commented on src/App.js
> +      <Route path="/:id" component={Good} />
А как на страницу продукта попасть?) http://s.csssr.ru/U0FMPH83W/20210224191459.mp4

2021-02-24 16:28 UTC, vislogurov commented on src/pages/NotFound.js
> +  const handleClick = (event) => {
А почему не `Link`, который ведёт на главную? кажется можно обойтись без хенделера.
Вообще это "звоночек", если ты юзаешь роутер, но при этом роутинг хэндлишь "руками"

2021-02-24 16:28 UTC, vislogurov commented on src/pages/NotFound.js
> +  const handleClick = (event) => {
Плюс это копипаста поведения из Good. Этого явно можно и нужно избежать.

2021-02-24 16:28 UTC, vislogurov commented on src/components/LinkArrow/index.js
> +    <StyledLink href={href} onClick={onClick}>
Неплохо бы в ссылку ещё передавать параметры для target/nofollow. Это удобно, когда можно указать на "открывание в новом окне"

2021-02-25 10:02 UTC, i-obraztsov commented on src/App.js
> +      <Route path="/:id" component={Good} />
Выглядит не очень )
А точно все изменения подтянулись?
На видео я вижу только 3 страницы и фильтры не применялись, хотя их должно быть больше, так же должны быть эффекты наведения на карточки, которые в наличии.
В общем я проверил у себя ещё раз в safari, ff и chrome и  такое не удалось воспроизвести

2021-02-25 19:41 UTC, i-obraztsov commented on src/pages/NotFound.js
> +  const handleClick = (event) => {
Я так сделал, чтобы возвращаться к предыдущему состоянию, например, если были выбраны категория или, страница, то вернуться туда откуда пришёл, а не кликать от главное, но кажется это какая-то не реальная ситуация )

2021-02-28 11:21 UTC, vislogurov approved these changes

2021-02-28 12:20 UTC, merged