Task 9 :: API
i-obraztsov/junior-course-boilerplate pull request #9
Opened 2021-02-28 17:44 UTC by i-obraztsov

2021-03-02 10:02 UTC, vislogurov requested changes

2021-03-02 10:02 UTC, vislogurov commented on src/components/Filter/index.js
> +      return null;
А точно ли null нужен? Получается у тебя форма с фильтрами вовсе исчезнет — криво с точки зрения UI. Повесь на неё какой нибудь disabled стиль. И тогда при ошибках ну нежно будет рендерить дерево заново.

2021-03-02 10:02 UTC, vislogurov commented on src/components/Product/index.js
> +    if (error) {
Тут тоже самое — что увидит пользователь, если возникнет ошибка?

2021-03-02 10:02 UTC, vislogurov commented on src/components/Product/index.js
> +      getProducts();
А зачем внутри _отдельного_  продукта нужен вызов getProducts? Ты же уровнем выше в самом списке уже установил все значения для фильтров. Непонятно

2021-03-02 10:02 UTC, vislogurov commented on src/modules/products.js
> +export const fetchProducts = async () => {
Если ошибка случится в этом методе, то как её отловить?

2021-03-15 19:25 UTC, i-obraztsov commented on src/components/Product/index.js
> +      getProducts();
Я это сделал тут на тот случай, если переход был по прямой ссылке, и тогда понадобятся продукты

2021-03-15 19:30 UTC, i-obraztsov commented on src/components/Filter/index.js
> +      return null;
Тут согласен, но я придерживался макета) и задания, там сказано, что контента не должно быть видно)

2021-03-15 19:35 UTC, i-obraztsov commented on src/modules/products.js
> +export const fetchProducts = async () => {
Эта функция вызывается в getProducts, там она обёрнута в try/catch, и ошибку можно поймать там

2021-07-26 04:51 UTC, merged